title: 労働衛生ラボ
description: 現場と法令の「あいだ」をつなぐ学習サイト
url: https://rodoeisei-lab.github.io
baseurl: "/rodoeisei-lab"
markdown: kramdown
permalink: pretty

collections:
  guides:
    output: true
    permalink: /guides/:name/
  updates:
    output: true
    permalink: /updates/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page

community:
  discussions_url: "https://github.com/rodoeisei-lab/rodoeisei-lab/discussions"
  discord_invite_url: ""

community_url: "https://github.com/rodoeisei-lab/rodoeisei-lab/discussions"
google_form_qa_embed_url: "https://docs.google.com/forms/d/e/1FAIpQLSeS4fA8gD3V8f3rY2rQx6x8q7rA0n4m9YwJ5K2L1M3N6P7Q8A/viewform?embedded=true"
qa_form_url: "https://docs.google.com/forms/d/e/1FAIpQLSeS4fA8gD3V8f3rY2rQx6x8q7rA0n4m9YwJ5K2L1M3N6P7Q8A/viewform"
